DECLARE @ANOFIM INT, @ANO INT, @MES INT, @VANO VARCHAR(4), @VMES VARCHAR(2)
SET     @ANO = 2009
SET     @ANOFIM = (SELECT MAX(SUBSTRING(CQ0_DATA,1,4)) FROM CQ0150)
IF (object_id('tempdb..#TEMP99') is null) 
  CREATE TABLE #TEMP99 (ANO VARCHAR(4), FILIAL VARCHAR(2), CONTA VARCHAR(20), DESCRICAO VARCHAR(40), MES VARCHAR(2), VALOR FLOAT)
  DELETE FROM #TEMP99
   WHILE @ANO < @ANOFIM BEGIN
      SET @VANO = CAST(@ANO AS VARCHAR)
      SET @MES = 1
	  WHILE @MES <= 12 BEGIN
	    SET @VMES = RIGHT('0'+CAST(@MES AS VARCHAR),2)
	    INSERT INTO #TEMP99 
		SELECT @VANO, X.FILIAL, X.CONTA, X.DESCRICAO, @VMES, 
		  CASE WHEN SUBSTRING(X.CONTA,1,1) = '1' THEN ROUND(X.DEBITO-X.CREDITO,2) ELSE ROUND(X.DEBITO-X.CREDITO,2) END AS VALOR
		FROM ( 
		SELECT D3.FILIAL, D3.CONTA, D3.DESCRICAO, 
				(SELECT SUM(X1.CQ0_DEBITO)  FROM CQ0150 X1 WITH (NOLOCK) WHERE X1.D_E_L_E_T_ <> '*'   AND X1.CQ0_TPSALD = '1'
				AND X1.CQ0_FILIAL = D3.FILIAL AND X1.CQ0_CONTA = D3.CONTA AND SUBSTRING(X1.CQ0_DATA,1,6) <= @VANO+@VMES
				) AS DEBITO,
				(SELECT SUM(X2.CQ0_CREDIT)  FROM CQ0150 X2 WITH (NOLOCK) WHERE X2.D_E_L_E_T_ <> '*'   AND X2.CQ0_TPSALD = '1'
				AND X2.CQ0_FILIAL = D3.FILIAL AND X2.CQ0_CONTA = D3.CONTA AND SUBSTRING(X2.CQ0_DATA,1,6) <= @VANO+@VMES
				) AS CREDITO
		FROM (
			SELECT DISTINCT D1.CQ0_FILIAL AS FILIAL, D1.CQ0_CONTA AS CONTA, C.CT1_DESC01 AS DESCRICAO
			FROM CQ0150 D1 WITH (NOLOCK) 
			INNER JOIN CT1150 C WITH (NOLOCK) ON (C.CT1_CONTA = D1.CQ0_CONTA AND C.D_E_L_E_T_ <> '*')
			WHERE D1.D_E_L_E_T_ <> '*' 
			AND D1.CQ0_DATA >= '20090101' 
			AND CQ0_TPSALD = '1' AND SUBSTRING(D1.CQ0_CONTA,1,1) IN ('1','2')      
		) D3
		) X
		SET @MES = @MES + 1
	  END;
	  SET @ANO = @ANO + 1
  END;
SELECT M.ANO, M.FILIAL, M.CCUSTO,M.CONTA, M.DESCRICAO, ISNULL(M.[JAN.],0) AS [JAN.],ISNULL(M.[FEV.],0) AS [FEV.],
ISNULL(M.[MAR.],0) AS [MAR.], ISNULL(M.[ABR.],0) AS [ABR.],ISNULL(M.[MAI.],0) AS [MAI.],
ISNULL(M.[JUN.],0) AS [JUN.], ISNULL(M.[JUL.],0) AS [JUL.],ISNULL(M.[AGO.],0) AS [AGO.],
ISNULL(M.[SET.],0) AS [SET.], ISNULL(M.[OUT.],0) AS [OUT.],ISNULL(M.[NOV.],0) AS [NOV.],ISNULL(M.[DEZ.],0) AS [DEZ.]
FROM (
SELECT ANO, FILIAL, CCUSTO, CONTA, DESCRICAO, [01] as 'JAN.',[02] as 'FEV.',[03] as 'MAR.',[04] as 'ABR.',
[05] as 'MAI.',[06] as 'JUN.',[07] as 'JUL.',[08] as 'AGO.',[09] as 'SET.',[10] as 'OUT.',
[11] as 'NOV.',[12] as 'DEZ.'
FROM (
SELECT ANO, FILIAL, '99999' AS CCUSTO, CONTA, DESCRICAO, MES, VALOR 
FROM #TEMP99

UNION ALL

SELECT D2.ANO COLLATE Latin1_General_BIN,
D2.FILIAL COLLATE Latin1_General_BIN,
CASE WHEN D2.CCUSTO = '' THEN '99999' ELSE D2.CCUSTO COLLATE Latin1_General_BIN END AS CCUSTO, 
D2.CONTA COLLATE Latin1_General_BIN, 
D2.DESCRICAO COLLATE Latin1_General_BIN, D2.MES COLLATE Latin1_General_BIN, ROUND(D2.DEBITO-D2.CREDITO,2) AS VALOR  
FROM (
SELECT D1.ANO,D1.FILIAL, D1.CCUSTO, D1.CONTA, D1.DESCRICAO, D1.MES, ROUND(SUM(D1.VALOR_CREDITO),2) AS CREDITO, ROUND(SUM(D1.VALOR_DEBITO),2) AS DEBITO  
FROM (
SELECT SUBSTRING(MC.CT2_DATA,1,4) AS ANO, MC.CT2_FILIAL AS FILIAL, MC.CT2_CCC AS CCUSTO, MC.CT2_CREDIT AS CONTA,
CC.CT1_DESC01 AS DESCRICAO,SUBSTRING(MC.CT2_DATA,5,2) AS MES, ROUND(MC.CT2_VALOR,2) AS VALOR_CREDITO, 0 AS VALOR_DEBITO
FROM CT2150 MC WITH (NOLOCK)
INNER JOIN CT1150 CC WITH (NOLOCK) ON (CC.CT1_CONTA = MC.CT2_CREDIT)
WHERE MC.D_E_L_E_T_ <> '*'
AND MC.CT2_DATA >= '20150101'
AND SUBSTRING(MC.CT2_CREDIT,1,1) = '3'
AND MC.CT2_ROTINA <> 'CTBA211'
AND MC.CT2_TPSALD = '1'
UNION ALL
SELECT SUBSTRING(MD.CT2_DATA,1,4) AS ANO, MD.CT2_FILIAL AS FILIAL, MD.CT2_CCD AS CCUSTO, MD.CT2_DEBITO AS CONTA,
CD.CT1_DESC01 AS DESCRICAO,SUBSTRING(MD.CT2_DATA,5,2) AS MES, 0  AS VALOR_CREDITO, ROUND(MD.CT2_VALOR,2) AS VALOR_DEBITO
FROM CT2150 MD WITH (NOLOCK)
INNER JOIN CT1150 CD WITH (NOLOCK) ON (CD.CT1_CONTA = MD.CT2_DEBITO)
WHERE MD.D_E_L_E_T_ <> '*'
AND MD.CT2_DATA >= '20150101'
AND SUBSTRING(MD.CT2_DEBITO,1,1) = '3'
AND MD.CT2_ROTINA <> 'CTBA211'
AND MD.CT2_TPSALD = '1'
) D1
GROUP BY D1.ANO,D1.FILIAL, D1.CCUSTO, D1.CONTA, D1.DESCRICAO, D1.MES
) D2
) W
PIVOT (SUM(VALOR) FOR MES IN ([01],[02],[03],[04],[05],[06],[07],[08],[09],[10],[11],[12]))Z
) M

 


